# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "MMikael's staff"
description: My personal projects site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: MMikael_18
github_username: MMikael18

# Build settings
markdown: kramdown
# Setup
collections:
- carts_collection

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "carts"
      type: "carts_collection" # previously `page` in Jekyll 2.2.
    values:
      layout: "default" # overrides previous default layout
